### ISSUE TITLE
需要matrix+vulcan配置

### ISSUE THREAD

**Issue by Cjjj-sys** [TalentsDX/Talents-anticheat-config#1]
能不能加一个matrix+vulcan的配置

**Comment by TalentsDX** [comment]
即将到来

**Comment by TalentsDX** [comment]
> 能不能加一个matrix+vulcan的配置

Vulcan已发布！请自行搭配Matrix配置即可
https://github.com/TalentsDX/Talents-anticheat-config/releases/tag/Vulcan-1.0.0
