### ISSUE TITLE
matrix+grim(版本已经更新)

### ISSUE THREAD

**Issue by 2053740844** [TalentsDX/Talents-anticheat-config#3]
各种客户端均可看到假人且不经意打到假人会直接踢。有时不知道怎么就卡刀。combat检测过于严格；cps到20多容易踢。

**Comment by TalentsDX** [comment]
https://github.com/TalentsDX/Talents-anticheat-config/releases/tag/Grim%2BMatrix-V1.0.1-test

**Comment by TalentsDX** [comment]
尝试修复，有问题请尽快回复我
