### ISSUE TITLE
[新配置] <简单说明>

### ISSUE THREAD

**Issue by WqsHackidc** [TalentsDX/Talents-anticheat-config#4]
### 此请求是否与错误有关?

不是

### 描述请求.

希望添加TaKa+Vulcan组合

### 还有别的吗？?

没用

**Comment by TalentsDX** [comment]
请告诉我take反作弊的链接

**Comment by WqsHackidc** [comment]
https://www.spigotmc.org/resources/taka-anticheat-takaac-cheap-and-reliable-solution.45167/ 已停更

**Comment by TalentsDX** [comment]
> https://www.spigotmc.org/resources/taka-anticheat-takaac-cheap-and-reliable-solution.45167/ 已停更

或许我去配置一个早在2021年4月就停产的反作弊并不是个好主意，伙计

**Comment by TalentsDX** [comment]
> 你可以尝试配置kauri https://www.spigotmc.org/resources/kauri-anticheat-best-in-class-performance-destroy-cheaters-1-7-10-1-18-2.101667/

可能将在近期更新kauri的优化配置

**Comment by TalentsDX** [comment]
> 你可以尝试配置kauri https://www.spigotmc.org/resources/kauri-anticheat-best-in-class-performance-destroy-cheaters-1-7-10-1-18-2.101667/

很不幸，在我测试kauri的时候只要稍微有一点延迟都会进行一个及时的拉回，让我很难受，kauri对我来说是很差的误判反作弊
