### ISSUE TITLE
[新配置] <简单说明>

### ISSUE THREAD

**Issue by WqsHackidc** [TalentsDX/Talents-anticheat-config#5]
### 此请求是否与错误有关?

没用

### 描述请求.

希望添加 Hawk+Vulcan组合https://www.spigotmc.org/resources/hawk-anticheat-mc-1-7-10-1-8-8.40343/

**Comment by TalentsDX** [comment]
很抱歉原版hawk到现在调试配置已经没有太大改进的地方，并且已经停更，建议自行魔改hawk来进行hawk的改进

**Comment by WqsHackidc** [comment]
hawk并没用停跟 github上的hawk是2201版本 spigotmc是2008

**Comment by TalentsDX** [comment]
麻烦您提供一下github项目地址

**Comment by WqsHackidc** [comment]
https://github.com/HawkAnticheat/Hawk

**Comment by Dreeam-qwq** [comment]
> 麻烦提供2201构建

You can get dev builds in their discord channel
https://ptb.discord.com/channels/347596353817542657/562023411937705984/1045160423076397117
